upstream servidor_django {
    server web:8000;
}

server {
    listen 80;

    # 1. Tudo que for acesso normal, joga para o Python (Django)
    location / {
        proxy_pass http://servidor_django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # 2. Quando o HTML pedir CSS ou JS, o Nginx entrega direto da pasta
    location /static/ {
        alias /app/src/static/;
    }

    # 3. Quando o coordenador quiser ver a foto do foco de dengue, o Nginx entrega
    location /media/ {
        alias /app/src/media/;
    }
}