# Generated by Django 4.2.29 on 2026-03-10 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Agente')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('quarteirao', models.CharField(max_length=50, verbose_name='Quarteirão/Quarteirão Lote')),
                ('tipo', models.CharField(choices=[('R', 'Residencial'), ('C', 'Comercial'), ('T', 'Terreno Baldio'), ('P', 'Ponto Estratégico')], default='R', max_length=1, verbose_name='Tipo de Imóvel')),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(help_text='Marque o ponto exato no mapa', srid=4326, verbose_name='Localização GPS')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Visita')),
                ('status', models.CharField(choices=[('N', 'Normal (Inspecionado)'), ('F', 'Fechado'), ('R', 'Recusado')], default='N', max_length=1, verbose_name='Status da Visita')),
                ('foco_mosquito_encontrado', models.BooleanField(default=False, verbose_name='Foco de Mosquito Encontrado?')),
                ('tratamento_aplicado', models.BooleanField(default=False, verbose_name='Tratamento Químico/Mecânico Aplicado?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endemias.agente', verbose_name='Agente Responsável')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='endemias.imovel', verbose_name='Imóvel Visitado')),
            ],
        ),
    ]
