# Generated by Django 4.2.29 on 2026-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endemias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='foco_mosquito_encontrado',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='tratamento_aplicado',
        ),
        migrations.AddField(
            model_name='visita',
            name='adulticida_qtde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Adulticida - Qtde (cargas)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='adulticida_tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adulticida - Tipo'),
        ),
        migrations.AddField(
            model_name='visita',
            name='amostras_coletadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de Tubitos/Amostras Coletadas'),
        ),
        migrations.AddField(
            model_name='visita',
            name='dep_A1',
            field=models.PositiveIntegerField(default=0, verbose_name="A1 (Caixa d'água elevado)"),
        ),
        migrations.AddField(
            model_name='visita',
            name='dep_A2',
            field=models.PositiveIntegerField(default=0, verbose_name='A2 (Outros armazenamentos baixo)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='dep_B',
            field=models.PositiveIntegerField(default=0, verbose_name='B (Pequenos depósitos móveis)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='dep_C',
            field=models.PositiveIntegerField(default=0, verbose_name='C (Depósitos fixos)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='dep_D1',
            field=models.PositiveIntegerField(default=0, verbose_name='D1 (Pneus e materiais rodantes)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='dep_D2',
            field=models.PositiveIntegerField(default=0, verbose_name='D2 (Lixo/Recipientes plásticos)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='dep_E',
            field=models.PositiveIntegerField(default=0, verbose_name='E (Depósitos naturais)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='depositos_eliminados',
            field=models.PositiveIntegerField(default=0, verbose_name='Depósitos Eliminados'),
        ),
        migrations.AddField(
            model_name='visita',
            name='larvicida_1_dep_tratados',
            field=models.PositiveIntegerField(default=0, verbose_name='Larvicida 1 - Depósitos Tratados'),
        ),
        migrations.AddField(
            model_name='visita',
            name='larvicida_1_qtde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Larvicida 1 - Qtde (g)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='larvicida_1_tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Larvicida 1 - Tipo'),
        ),
        migrations.AddField(
            model_name='visita',
            name='larvicida_2_dep_tratados',
            field=models.PositiveIntegerField(default=0, verbose_name='Larvicida 2 - Depósitos Tratados'),
        ),
        migrations.AddField(
            model_name='visita',
            name='larvicida_2_qtde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Larvicida 2 - Qtde (g)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='larvicida_2_tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Larvicida 2 - Tipo'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('R', 'Residencial'), ('C', 'Comercial'), ('T', 'Terreno Baldio'), ('P', 'Ponto Estratégico'), ('O', 'Outros')], default='R', max_length=1, verbose_name='Tipo de Imóvel'),
        ),
    ]
