# Generated by Django 4.2.29 on 2026-03-12 21:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endemias', '0002_remove_visita_foco_mosquito_encontrado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={},
        ),
        migrations.RemoveField(
            model_name='agente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='visita',
            name='ciclo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_visita',
            field=models.DateField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='quantidade_larvas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visita',
            name='semana_epidemiologica',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agente',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, default='S/N', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quarteirao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('R', 'Residencial'), ('C', 'Comercial'), ('TB', 'Terreno Baldio'), ('PE', 'Ponto Estratégico'), ('O', 'Outros')], default='R', max_length=2),
        ),
        migrations.AlterField(
            model_name='visita',
            name='adulticida_qtde',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='adulticida_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='agente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='endemias.agente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='amostras_coletadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dep_A1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dep_A2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dep_B',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dep_C',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dep_D1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dep_D2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dep_E',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='depositos_eliminados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='endemias.imovel'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='larvicida_1_dep_tratados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='larvicida_1_qtde',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='larvicida_1_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='larvicida_2_dep_tratados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='larvicida_2_qtde',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='visita',
            name='larvicida_2_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('N', 'Normal (Inspecionado)'), ('F', 'Fechada'), ('R', 'Recusada')], default='N', max_length=1),
        ),
    ]
