# Generated by Django 4.2.29 on 2026-03-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endemias', '0003_alter_imovel_options_remove_agente_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data_visita',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
